name: Release Notes CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "apps/release-notes/**"

defaults:
  run:
    shell: bash
    working-directory: ./apps/release-notes

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov/sbc-producthub'

    steps:
      - uses: actions/checkout@v3
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install
      - name: run build
        env:
          ZENHUB_APIKEY: ${{  secrets.ZENHUB_APIKEY  }}
        run: |
          pnpm run build
      - name: Linting
        run: |
          pnpm run lint

  testing-coverage:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install
      - name: Testing
        run: |
          pnpm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: releasenotes
          name: codecov-release-notes
          fail_ci_if_error: true

  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install

      - name: run test
        env:
          ZENHUB_APIKEY: ${{  secrets.ZENHUB_APIKEY  }}
        run: |
          pnpm run build-check